name: Stages Callback
on:
  push:
    branches:
      - dev
      - stage
jobs:
  callback:
    runs-on: ubuntu-latest
    steps:
      - name: "Get Merged SHA"
        id: mergedsha
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh api --jq '.parents[1].sha' /repos/testigoelectoral/terraform/commits/${{ github.event.pull_request.head.sha }}

      - name: "Get Merged SHA"
        shell: bash
        id: actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export QUERY="[.[]|select(.conclusion==\"failure\")|select(.headSha==\"${{ steps.mergedsha.outputs }}\")|.databaseId]|sort|unique|.[]"
          gh run list --workflow "Check Stages" --json conclusion,headSha,databaseId --jq $QUERY

      - name: "Get Merged SHA"
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: for actionId in ${{ steps.actions.outputs }}; do gh run rerun ${actionId} || true; done
