name: Stages Callback
on:
  push:
    branches:
      - dev
      - stage
jobs:
  callback:
    runs-on: ubuntu-latest
    steps:
      - name: "Get Merged SHA"
        id: mergedsha
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get Merged SHA
          export QUERY=".parents[1].sha"
          echo "QUERY: ${QUERY}"
          export SHA=$(gh api --jq ${QUERY} /repos/testigoelectoral/terraform/commits/${{ github.event.after }})
          echo "SHA: ${SHA}"
          echo "::set-output name=sha::${SHA}"

      - name: "Get Actions to re-run"
        shell: bash
        id: actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get Actions to re-run
          export SHA=${{ steps.mergedsha.outputs.sha }}
          echo "SHA: ${SHA}"
          # export QUERY="[.workflow_runs[]|select(.name==\"Check Stages\")|select(.head_sha==\"${SHA}\")|.id]|sort|unique|.[]"
          export QUERY='.workflow_runs[]|with_entries(select([.key]|inside(["name","head_sha","id"])))'
          echo "QUERY: ${QUERY}"
          export ACTIONS=$(gh api --jq ${QUERY} --method GET -f status=failure -f event=pull_request /repos/testigoelectoral/terraform/actions/runs)
          echo "ACTIONS: ${ACTIONS}"
          echo "::set-output name=actions::${ACTIONS}"

      - name: "Rerun actions"
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Rerun actions
          export ACTIONS=${{ steps.actions.outputs.actions }}
          echo "ACTIONS: ${ACTIONS}"
          # for actionId in ${{ steps.actions.outputs.actions }}; do gh run rerun ${actionId} || true; done
