name: Stages Callback
on:
  push:
    branches:
      - dev
      - stage
jobs:
  callback:
    runs-on: ubuntu-latest
    steps:
      - name: "Get Merged SHA"
        id: mergedsha
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get Merged SHA
          export SHA=$(gh api --jq '.parents[1].sha' /repos/testigoelectoral/terraform/commits/${{ github.event.after }})
          echo "::set-output name=sha::${SHA}"
          echo "SHA: ${SHA}"

      - name: "Get Actions to re-run"
        shell: bash
        id: actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export SHA=${{ steps.mergedsha.outputs.sha }}
          echo "SHA: ${SHA}"
          export QUERY="[.workflow_runs[]|select(.name==\"Check Stages\")|select(.head_sha==\"${SHA}\")|.id]|sort|unique|.[]"
          echo "QUERY: ${QUERY}"
          export ACTIONS=$(gh api --jq $QUERY --method GET -f status=failure -f event=pull_request /repos/testigoelectoral/terraform/actions/runs)
          echo "::set-output name=actions::${ACTIONS}"
          echo "ACTIONS: ${ACTIONS}"

      - name: "Rerun actions"
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${{ github.event.before }}
          export ACTIONS=${{ steps.actions.outputs.actions }}
          echo "ACTIONS: ${ACTIONS}"
          for actionId in ${{ steps.actions.outputs.actions }}; do gh run rerun ${actionId} || true; done
